package tablas;
// Generated 4/04/2018 02:40:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private int idEstacion;
     private String nombre;
     private BigDecimal longitud;
     private BigDecimal latitud;
     private BigDecimal altura;
     private String descripcion;
     private Set<Sensor> sensors = new HashSet<Sensor>(0);

    public Estacion() {
    }

	
    public Estacion(int idEstacion) {
        this.idEstacion = idEstacion;
    }
    
    public Estacion(int idEstacion, String nombre, BigDecimal longitud, BigDecimal latitud, BigDecimal altura, String descripcion, Set<Sensor> sensors) {
       this.idEstacion = idEstacion;
       this.nombre = nombre;
       this.longitud = longitud;
       this.latitud = latitud;
       this.altura = altura;
       this.descripcion = descripcion;
       this.sensors = sensors;
    }
   
    public int getIdEstacion() {
        return this.idEstacion;
    }
    
    public void setIdEstacion(int idEstacion) {
        this.idEstacion = idEstacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    public BigDecimal getAltura() {
        return this.altura;
    }
    
    public void setAltura(BigDecimal altura) {
        this.altura = altura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Sensor> getSensors() {
        return this.sensors;
    }
    
    public void setSensors(Set<Sensor> sensors) {
        this.sensors = sensors;
    }




}


