package tablas;
// Generated 4/04/2018 02:40:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Medicion generated by hbm2java
 */
public class Medicion  implements java.io.Serializable {


     private Integer idMedicion;
     private Sensor sensor;
     private Date fecha;
     private BigDecimal datoObtenido;
     private Date hora;

    public Medicion() {
    }

    public Medicion(Sensor sensor, Date fecha, BigDecimal datoObtenido, Date hora) {
       this.sensor = sensor;
       this.fecha = fecha;
       this.datoObtenido = datoObtenido;
       this.hora = hora;
    }
   
    public Integer getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(Integer idMedicion) {
        this.idMedicion = idMedicion;
    }
    public Sensor getSensor() {
        return this.sensor;
    }
    
    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getDatoObtenido() {
        return this.datoObtenido;
    }
    
    public void setDatoObtenido(BigDecimal datoObtenido) {
        this.datoObtenido = datoObtenido;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


