package tablas;
// Generated 4/04/2018 02:40:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiposensor generated by hbm2java
 */
public class Tiposensor  implements java.io.Serializable {


     private int idTipoSensor;
     private String tipoSensor;
     private Set<Sensor> sensors = new HashSet<Sensor>(0);

    public Tiposensor() {
    }

	
    public Tiposensor(int idTipoSensor) {
        this.idTipoSensor = idTipoSensor;
    }

    public Tiposensor(int idTipoSensor, String tipoSensor) {
        this.idTipoSensor = idTipoSensor;
        this.tipoSensor = tipoSensor;
    }
    
    public Tiposensor(int idTipoSensor, String tipoSensor, Set<Sensor> sensors) {
       this.idTipoSensor = idTipoSensor;
       this.tipoSensor = tipoSensor;
       this.sensors = sensors;
    }
   
    public int getIdTipoSensor() {
        return this.idTipoSensor;
    }
    
    public void setIdTipoSensor(int idTipoSensor) {
        this.idTipoSensor = idTipoSensor;
    }
    public String getTipoSensor() {
        return this.tipoSensor;
    }
    
    public void setTipoSensor(String tipoSensor) {
        this.tipoSensor = tipoSensor;
    }
    public Set<Sensor> getSensors() {
        return this.sensors;
    }
    
    public void setSensors(Set<Sensor> sensors) {
        this.sensors = sensors;
    }




}


